apiVersion: v1
kind: Service
metadata: 
  name: bluegreen-backend 
  labels: 
    name: bluegreen-backend
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector: 
      app: backend-green
  type: LoadBalancer
